### ISSUE TITLE
Results on MS-COCO 5K with noise ratio 0

### ISSUE THREAD

**Issue by qxzha** [hhc1997/L2RM#2]
nice work! Could you please provide the results on well-annotated MS-COCO 5K, i.e., MRate is 0.?
Or could you please provide the pre-trained models on MS-COCO?

**Comment by hhc1997** [comment]
Hi， @qxzha
Sorry for my late reply.
The results on well-annotated MS-COCO 5K are:
![image](https://github.com/user-attachments/assets/541bb54e-a535-4552-8ebc-c1a2a91cb38b)

**Comment by qxzha** [comment]
Thanks a lot! I will report this result in the following research.

**Comment by qxzha** [comment]
It fixed my concerns.
