### ISSUE TITLE
About the OT Loss

### ISSUE THREAD

**Issue by RIU-13** [hhc1997/L2RM#4]
您好
OT Loss只计算了随机选择的reconstructed pairs的损失，那这个loss的数值有什么参考价值吗？我跑出来的loss一直在随机变化，应该是正常的吧？
请问您有没有训练全过程的training log，想参考一下各阶段loss变化和指标提升的情况

**Comment by hhc1997** [comment]
[F02_SGR_3407.zip](https://github.com/user-attachments/files/16557255/F02_SGR_3407.zip)
@RIU-13 这是SGR模型 Flickr30K 0.2噪声的一次训练，供参考。随着训练进行，cost_loss总体降低还是比较明显的, epoch 1时2.2238e+00，epoch 35时5.1055e-01。

可能参数无法适应你的任务和模型。

**Comment by RIU-13** [comment]
> [F02_SGR_3407.zip](https://github.com/user-attachments/files/16557255/F02_SGR_3407.zip) @RIU-13 这是SGR模型 Flickr30K 0.2噪声的一次训练，供参考。随着训练进行，cost_loss总体降低还是比较明显的, epoch 1时2.2238e+00，epoch 35时5.1055e-01。
> 
> 可能参数无法适应你的任务和模型。

ok thanks a lot！~~~
