### ISSUE TITLE
训练速度

### ISSUE THREAD

**Issue by haiquan-yu** [hhc1997/L2RM#5]
你好，我在用你的代码训练时发现速度特别慢，用的4090，训练了一天了还没跑完，请问这是正常的速度还是我的配置有问题

**Comment by hhc1997** [comment]
> 你好，我在用你的代码训练时发现速度特别慢，用的4090，训练了一天了还没跑完，请问这是正常的速度还是我的配置有问题

你好。你跑的哪个数据集，MS-COCO比较大会久一些，其他的一天内都可以跑完。

**Comment by haiquan-yu** [comment]
嗷嗷，那没问题了我跑的就是coco，非常感谢
