### ISSUE TITLE
cannot import name 'GeneralMixtureModel' from 'pomegranate' 

### ISSUE THREAD

**Issue by zqxie77** [hhc1997/L2RM#6]
Traceback (most recent call last):
  File "main_L2RM.py", line 5, in <module>
    from pomegranate import GeneralMixtureModel,TrueBetaDistribution
ImportError: cannot import name 'GeneralMixtureModel' from 'pomegranate' (/home/****/anaconda3/envs/L2RM/lib/python3.8/site-packages/pomegranate-1.1.0-py3.8.egg/pomegranate/__init__.py)

excuse me
what can I do

**Comment by zqxie77** [comment]
![image](https://github.com/user-attachments/assets/f26634c7-3a6c-47e2-83af-169542bc931c)
我按照这个做了呀

**Comment by hhc1997** [comment]
> ![image](https://private-user-images.githubusercontent.com/102861134/375191291-f26634c7-3a6c-47e2-83af-169542bc931c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Mzk4ODQsIm5iZiI6MTcyODUzOTU4NCwicGF0aCI6Ii8xMDI4NjExMzQvMzc1MTkxMjkxLWYyNjYzNGM3LTNhNmMtNDdlMi04M2FmLTE2OTU0MmJjOTMxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNTUzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjFjZjZhNzllYjFiN2Q1ZWIxMjg5Y2JhNjE1YWE1ZDk5MmRjNzAxMTVkMjY4MGRhYWU2ZDVjMDQyNzIwMTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SiH1Y0aiLKRw8979YZhn3d_lAMKyImwisTPWjUic3j0) 我按照这个做了呀

Please refer to [https://github.com/hhc1997/MSCN/issues/4#issuecomment-1761211409] and [https://github.com/hhc1997/MSCN/issues/5#issuecomment-1753109277](url).

**Comment by zqxie77** [comment]
thank you

**Comment by ChinaWangYu666** [comment]
> ![image](https://private-user-images.githubusercontent.com/102861134/375191291-f26634c7-3a6c-47e2-83af-169542bc931c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODk5NTUsIm5iZiI6MTczMDY4OTY1NSwicGF0aCI6Ii8xMDI4NjExMzQvMzc1MTkxMjkxLWYyNjYzNGM3LTNhNmMtNDdlMi04M2FmLTE2OTU0MmJjOTMxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDI2ZWNiMTUyZjViZTBkZTQ5ODJjYjI4Y2U3YjUzODUxYzMyOWM0MDVhZTk3OGRjMTcxZWZhYWRlOTEyNzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sWigvKInQSHfAUYosHBGT6kFcj8Qv0mX_kwpZtxdc5Q) 我按照这个做了呀

按照这个仍然报错

**Comment by hhc1997** [comment]
> > ![image](https://private-user-images.githubusercontent.com/102861134/375191291-f26634c7-3a6c-47e2-83af-169542bc931c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODk5NTUsIm5iZiI6MTczMDY4OTY1NSwicGF0aCI6Ii8xMDI4NjExMzQvMzc1MTkxMjkxLWYyNjYzNGM3LTNhNmMtNDdlMi04M2FmLTE2OTU0MmJjOTMxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDI2ZWNiMTUyZjViZTBkZTQ5ODJjYjI4Y2U3YjUzODUxYzMyOWM0MDVhZTk3OGRjMTcxZWZhYWRlOTEyNzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sWigvKInQSHfAUYosHBGT6kFcj8Qv0mX_kwpZtxdc5Q) 我按照这个做了呀
> 
> 按照这个仍然报错

参考一下 [https://github.com/https://github.com/hhc1997/MSCN/issues/4#issuecomment-1761211409] 和[https://github.com/hhc1997/MSCN/issues/5#issuecomment-1753109277](https://github.com/hhc1997/L2RM/issues/url)
