### ISSUE TITLE
数据集究竟是如何加载的？

### ISSUE THREAD

**Issue by showmeyourcodehaha** [hhc1997/L2RM#8]
本人不是搞传统图文检索领域的，只是想要将您的方法迁移到我的任务上，传统的那几个数据集我没有，太大了，我也不太想下载。故没有实际运行此代码，因而有下面问题。
但是我看到代码中的：
class PrecompDataset(data.Dataset):
    """
    Load precomputed captions and image features
    Possible options: f30k_precomp, coco_precomp
    """
...
其中的注释“Load precomputed captions and image features”让我疑惑不解，这里的“captions and image features”是指什么？特征？不是吧，特征是由backbone产生的啊，在这里不可能是特征啊，所以这个类中的caption和image究竟是什么一个形式？

**Comment by hhc1997** [comment]
@showmeyourcodehaha  你可以参考下 [NCR](https://github.com/XLearning-SCU/2021-NeurIPS-NCR)中关于数据部分的说明，这里的输入已经经过了预处理，不是原始数据。至于原因，我认为是端到端训练的算力开销过高。
